apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: foo@acme.org
    privateKeySecretRef:
      name: letsencrypt-production-key
    http01: {}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: app-acme-systems
  namespace: central-bootstrap
spec:
  secretName: app-acme-systems-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: app.acme.org
  dnsNames:
  - app.acme.org
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - app.acme.org
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: api-acme-systems
  namespace: central-bootstrap
spec:
  secretName: api-acme-systems-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: api.acme.org
  dnsNames:
  - api.acme.org
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - api.acme.org
